keys:
    - &frahz age1kzz4nsy6enrfqukh5a5tgarsnhsu3qsg2ztyaukty0g0dys4qdlqw6qjjf
creation_rules:
    - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
      key_groups:
          - age:
              - *frahz
