{
  config,
  lib,
  pkgs,
  self,
  ...
}:
let
  inherit (lib) mkIf mkEnableOption;
  inherit (lib.lists) singleton;
  inherit (self.lib) toHyprconf;
  cfg = config.casa.programs.hyprland;
  toLua = lib.generators.toLua { };
in
{
  imports = [
    ./hypridle.nix
    ./hyprlock.nix
  ];

  options.casa.programs.hyprland = {
    enable = mkEnableOption "Enable Hyprland";
  };

  config = mkIf cfg.enable {
    programs.hyprland = {
      enable = true;
      xwayland.enable = true;
    };

    hjem.users.frahz = {
      xdg.config.files = {
        "hypr/hyprland.lua".text = ''
          -- Generated by Hjem.

          hl.on("hyprland.start", function()
            hl.exec_cmd("${lib.getExe' pkgs.dbus "dbus-update-activation-environment"} --systemd --all && systemctl --user stop graphical-session.target && systemctl --user start hyprland-session.target")
          end)

          hl.on("hyprland.shutdown", function()
            os.execute("systemctl --user stop hyprland-session.target && sleep 0.1")
          end)

          local cursorSize = ${toLua "22"}
          local fuzzel = ${toLua (lib.getExe pkgs.fuzzel)}
          local hyprlock = ${toLua (lib.getExe pkgs.hyprlock)}

        ''
        + builtins.readFile ./config.lua;

        "hypr/xdph.conf" = {
          generator = attrs: toHyprconf { inherit attrs; };
          value.screencopy = {
            custom_picker_binary = lib.getExe pkgs.hyprland-preview-share-picker;
            allow_token_by_default = true;
          };
        };
      };

      systemd.targets.hyprland-session = {
        description = "Hyprland compositor session";
        documentation = singleton "man:systemd.special(7)";
        bindsTo = singleton "graphical-session.target";
        wants = singleton "graphical-session-pre.target";
        after = singleton "graphical-session-pre.target";
        unitConfig.PropagatesStopTo = singleton "graphical-session.target";
      };
    };
  };
}
